package lain.mods.inputfix;

import java.util.Arrays;
import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

public class InjectedModContainer extends DummyModContainer
{

    public InjectedModContainer()
    {
        super(new ModMetadata());
        ModMetadata meta = getMetadata();
        meta.modId = "InputFix";
        meta.name = "InputFix";
        meta.version = "1.5.1";
        meta.authorList = Arrays.asList("Lain");
        meta.description = "InputFix is a way to enable multi word input via input methods in minecraft.";
        meta.credits = "pa001024 - for some nice tweaks";
        meta.autogenerated = false;
    }

    @Subscribe
    public void init(FMLPreInitializationEvent event)
    {
        Config.setup(event.getSuggestedConfigurationFile());
    }

    @Override
    public boolean registerBus(EventBus paramEventBus, LoadController paramLoadController)
    {
        paramEventBus.register(this);
        return true;
    }

}
